-- AlterTable
ALTER TABLE "Card" ALTER COLUMN "number" SET DATA TYPE VARCHAR(25),
ALTER COLUMN "cardholderName" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "securityCode" SET DATA TYPE TEXT,
ALTER COLUMN "password" SET DATA TYPE TEXT;
